// Other code...
// sb (was window.supabaseClient)
// Other code...
const data = sb.from("table");
// Other code...
const user = sb.auth;
// Other code...
const data2 = sb.from("table2");
// Other code...